blogapp/urls.py
from django.urls import path, include
from django.contrib import admin
from django.contrib.auth import authenticate, login
from .views import *
app_name = 'blogapp'


# A primary key of student is passed 
urlpatterns =[
	path('login/', LoginView.as_view(),name='login'),
	path('', HomeView.as_view(),name='home'),
	path('logout/', LogoutView.as_view(),name='logout'),	
	path('movie/', MovieListView.as_view(),name='movie'),
	path('contact/', ContactView.as_view(), name= 'contact'),
	path('about/', AboutView.as_view(), name= 'about' ),
	path('story/', StoryView.as_view(), name= 'story' ),
	path('service/', ServiceView.as_view(), name= 'service' ),
	path('login/', LoginView.as_view(), name = 'login'),
	path('location/', LocationView.as_view(), name = 'location'),
	path('student/list/', StudentListView.as_view(), name='studentlist'),
	path('book/list/', BookListView.as_view(), name='booklist'),
	path('student/<int:pk>/detail/',StudentDetailView.as_view(), name="studentdetail"),
	path('book/<int:pk>/detail/',BookDetailView.as_view(), name="bookdetail"),
	path('movie/list', MovieListView.as_view(), name='movielist'),
	path('movie/<int:pk>/detail/',MovieDetailView.as_view(), name="moviedetail"),
	path('base1/', Base1View.as_view(), name= 'base1' ),
	path('student/add',StudentCreateView.as_view(), name='studentcreate'),
	path('student/<int:pk>/update/',StudentUpdateView.as_view(),name='studentupdate'),
	path('book/add',BookCreateView.as_view(), name='bookcreate'),
	path('book/<int:pk>/update/',BookUpdateView.as_view(),name='bookupdate'),
	path('movie/add',MovieCreateView.as_view(), name='moviecreate'),
	path('movie/<int:pk>/update/',MovieUpdateView.as_view(),name='movieupdate'),
	path('student/<int:pk>/delete/',StudentDeleteView.as_view(),name='studentdelete'),
	path('news/',NewsView.as_view(),name='news'),
	path('search/result/', SearchResultView.as_view(), name = "searchresult")
	# path('movie/<int:pk>/delete/',MovieDeleteView.as_view(),name='moviedelete'),
	#path('book/<int:pk>/delete/',BookDeleteView.as_view(),name='bookdelete'),

]

blogproject/urls.py
from django.conf.urls.static import static
from django.conf import settings
from django.contrib import admin
from django.urls import path,include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blogapp.urls', namespace = 'blogapp' )),

]

urlpatterns += static(settings.STATIC_URL, document_root =settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

blogapp/models.py
from django.db import models
from django.utils import timezone
# Create your models here.
class Student(models.Model):
	name = models.CharField(max_length=150)
	grade = models.PositiveIntegerField()
	address = models.CharField(max_length=200, null=True, blank=True)
	image = models.ImageField(upload_to="student")
	email = models.EmailField()

	def __str__(self):
		return self.name


class Book(models.Model):
	name = models.CharField(max_length=150)
	author = models.CharField(max_length=150)
	published_date = models.DateField()
	edition = models.PositiveIntegerField()
	image = models.ImageField(upload_to="book")
	issued_by = models.ForeignKey(Student, on_delete = models.SET_NULL, null = True, blank = True)

	def __str__(self):
		return self.name



class Category(models.Model):
	news_category = models.CharField(max_length=100)

	def __str__(self):
		return self.news_category


class News(models.Model):
	title = models.CharField(max_length=500)
	content = models.TextField()
	writer = models.CharField(max_length=50, null=True)
	created_date = models.DateTimeField( default=timezone.now, null=True)
	published_date = models.DateTimeField( blank = False )
	category = models.ForeignKey(Category, on_delete = models.DO_NOTHING, null = True, blank = True)

	news_language = (
		('e', 'English'),
        ('n', 'Nepali'),
	)
	language = models.CharField(
        max_length=20,
        choices=news_language,
        default='e',
    )
	country = models.CharField(max_length=50,blank=True)
	image = models.ImageField(upload_to='news_',null=True)

	def post(self):
		self.created_date = timezone.now()
		self.save() 
		
	def __str__(self):
		#return '%s,%s,%s' %(self.name, self.rating)
		return self.title

# class Staff(models.Model):

industry = (
    	('h','Hollywood'),
    	('b','Bollywood'),
    	('t','Tollywood'),
    	('k','Kollywood'),
    )

class Movie(models.Model):
	name = models.CharField(max_length=150)
	director = models.CharField(max_length=30)
	actor = models.CharField(max_length=100,null=True)
	writer = models.CharField(max_length=50, null=True)
	created_date = models.DateTimeField( default=timezone.now, null=True)
	release_date = models.DateTimeField( blank = False )
	run_time = models.PositiveSmallIntegerField(default=120)
	rating = models.PositiveSmallIntegerField(default=2)
	language = models.CharField(max_length=50,blank=True)
	genre = (
        ('c', 'Comedy'),
        ('t', 'Thriller'),
        ('r', 'Romantic'),
        ('f', 'Fictional'),
        ('n', 'NonFictional'),
        ('h', 'Horror'),

    )
	genre_choices = models.CharField(
        max_length=20,
        choices=genre,
        default='r',
    )
   
	country = models.CharField(
		max_length=10,
		choices=industry,
		default='h',
		)
	poster = models.ImageField(upload_to='poster',null=True)

	def release(self):
		self.release_date = timezone.now()
		self.save() 
		
	def __str__(self):
		#return '%s,%s,%s' %(self.name, self.rating)
		return self.name

templates/base.html
{% load static %}

<!DOCTYPE html>
<html>
<head>

<link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
<link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
<link rel="stylesheet" href="{% static 'css/dataTables.bootstrap.min.css' %}">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">


<title>{% block title %}Pilot{% endblock %}</title>

</head>
<body>
  <div class="container-fluid">
    <div class="row">
      <div class="col-md-2">
        <span><a href="#"><h5> English </h5></a></span>
      </div>
      <div class="col-md-8 text-center">
        <span><h4>The Pilot design of the Home Page</h4></span>
      </div>
      <div class="col-md-2 ">
          <a href="#" class="fa fa-facebook" style="padding: 20px;"></a>
          <a href="#" class="fa fa-twitter" style="padding: 20px;"></a>
          <a href="#" class="fa fa-instagram" style="padding: 20px;"></a>
      </div>
    </div>  
      <nav class="navbar navbar-expand-lg navbar-light bg-primary" width=100% >
        <a href="{% url 'blogapp:home' %}" class="pull-left"><img src="/static/images/earth.png" class=" width ="30%" height="30"></a> 
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item {% block home %}{% endblock %}">
              <a class="nav-link" href="{% url 'blogapp:home' %}">Home </a>
            </li>
            <li class="nav-item{% block studentlist %}{% endblock %}">
              <a class="nav-link" href="{% url 'blogapp:studentlist' %}">StudentList</a>
            </li>
             <li class="nav-item {% block booklist %}{% endblock %}">
              <a class="nav-link" href="{% url 'blogapp:booklist'%}">BookList</a>
            </li>
            <li class="nav-item {% block movielist %}{% endblock %}">
              <a class="nav-link" href="{% url 'blogapp:movielist'%}">Movies</a>
            </li>
            <li class="nav-item {% block about %}{% endblock %}">
              <a class="nav-link" href="{% url 'blogapp:about'%}">About</a>
            </li>
            <li class="nav-item active {% block contact %}{% endblock %}">
              <a class="nav-link" href="{% url 'blogapp:contact'%}">Contact </a>
            </li>
          </ul>
            <form class="form-inline my-2 my-lg-0"  action="{% url 'blogapp:searchresult' %}"method="get" accept-charset="utf-8">
              <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
              <button class="btn btn-outline-success my-2 my-sm-0" type="submit"><i class="fa fa-search"></i></button>
            </form>
           <button class="btn btn-outline-success my-2 my-sm-0" type="submit"><a href="{% url 'blogapp:login' %}"> Login
           </button>
        </div>
      </nav>
    
  
  <div class="row">

    <h2>
      {% if request.user.is_authenticated %}
      <h2>Logged in as: </h2>
      {{ request.user.username }}<br>
      <a href="{% url 'blogapp:logout' %}">Logout</a>
      {% else %}
   <!--    <a href="{% url 'blogapp:login' %}">Login</a> -->
      {% endif %}
      {% block content %}

      {% endblock %}
    </h2>
  </div>
</div>
 




<script type="text/javascript" src="{% static 'js/jquery-3.3.1.min.js' %}" ></script>
<script type="text/javascript" src="{% static 'js/popper.min.js' %}" ></script>
<script type="text/javascript" src="{% static 'js/bootstrap.min.js' %}"></script>
<script type="text/javascript" src="{% static 'js/jquery.dataTables.min.js' %}"></script>
<script type="text/javascript" src="{% static 'js/dataTables.bootstrap.min.js' %}"></script>

<script>
// Get the video
var video = document.getElementById("myVideo");

// Get the button
var btn = document.getElementById("myBtn");

// Pause and play the video, and change the button text
function myFunction() {
  if (video.paused) {
    video.play();
    btn.innerHTML = "Pause";
  } else {
    video.pause();
    btn.innerHTML = "Play";
  }
}
</script>
</body>
</html>

templates/base1.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
	<title>Base1</title>
	<style type="text/css">ul {
  list-style-type: none;
  margin: 0;
  padding: 0;
  overflow: hidden;
  background-color: #333;
}

li {
  float: left;
}

li a {
  display: block;
  color: white;
  text-align: center;
  padding: 14px 16px;
  text-decoration: none;
}

/* Change the link color to #111 (black) on hover */
li a:hover {
  background-color: #111;
}

		ul{
			list-style-type: none;
			padding: 10px;
			margin:5px;
			display: inline;
		}
		nav{
			padding: 5px;
			width: 100%;
		/*	display: inline;*/

		}
		nav ul{
			float:left;
			display: inline;
		}
		nav ul li{
			float:left;
			display: inline;
		}
		nav ul li a{
			float: left;
			display: inline;
			padding: 8px;
  			background-color: #333;
		}
		a{
			display:block;
			padding: 5px;
			/*background-color: rgb(199, 55, 55);*/
		}
	</style>

</head>
<body>
<div class="con">
	<!-- <div class="row">
		<div class="col-md-3">
			<img src="/static/images/earth.png" class=" width ="30%" height="30"">
		</div>
		<div class="col-md-7"><h3>This is the home page</h3>
		</div>
		<div class="col-md-2">
			<ul>
				<a href="#" class="fa fa-facebook"></a>
          		<a href="#" class="fa fa-twitter"></a>
          		<a href="#" class="fa fa-instagram"></a>
			</ul>
		</div>
	</div> -->
	<nav>
		<ul>
			<li><h4><a href="#"> Home</a></h4></li>
			<li><h4><a href="#"> Services</a></h4></li>
			<li><h4><a href="#">Location</a></h4></li>
			<li><h4><a href="#">About us</a></h4></li>
		</ul>
		</nav>
	</div>
	<div class="row">
			<h1>This is the slider</h1>
	</div>

	<div class="row">
		
	<div class="col-md-3">
		<h1>fdsf</h1>
	</div>
	<div class="col-md-7">
		<h1>fdgdfgdf</h1>
	</div>
	<div class="col-md-2">
		<h2>frfgdf</h2>
	</div>


	</div>



	<div class="row">
		<div class="col-md-3">
			<p>content1</p>
		</div>
		<div class="col-md-7">
			<p>content2</p>
		</div>
		<div class="col-md-2">
			<h3>content3</h3>
		</div>

	</div>
	<div class="footer">
			This is the footer
	</div>
</div>
</body>
</html>

templates/bookdetail.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

<tr>
      <td>{{book.id}}</td>
      <td>{{book.name}}</td>
      <td>{{book.author}}</td>
      <td>{{book.published_date}}</td>
      <td>{{book.edition}}</td>
      <td>{{book.issued_by}}</td>
      <td><img src="{{book.image.url}}" class="img-fluid" width="200px"></th>
</tr>
<div id="fb-root"></div>
<script>
  window.fbAsyncInit = function() {
  FB.init({
    appId      : 'YOUR_APP_ID', // App ID
    channelUrl : '//WWW.YOUR_DOMAIN.COM/channel.html', // Channel File
    status     : true, // check login status
    cookie     : true, // enable cookies to allow the server to access the session
    xfbml      : true  // parse XFBML
  });
};

(function(d){
  var js, id = 'facebook-jssdk', ref = d.getElementsByTagName('script')[0];
  if (d.getElementById(id)) {return;}
  js = d.createElement('script'); js.id = id; js.async = true;
  js.src = "//connect.facebook.net/en_US/all.js";
  ref.parentNode.insertBefore(js, ref);
}(document));
</script>

...

<div
   class="fb-comments" 
   data-href="{{ my_object.slug }}" 
   data-num-posts="2" 
   data-width="470"></div>
<!-- <a href="https://www.facebook.com/sharer/sharer.php?u=example.org" target="_blank">
  Share on Facebook
</a>
 -->
  <!-- Load Facebook SDK for JavaScript -->
  <div id="fb-root"></div>
  <script>(function(d, s, id) {
    var js, fjs = d.getElementsByTagName(s)[0];
    if (d.getElementById(id)) return;
    js = d.createElement(s); js.id = id;
    js.src = "https://connect.facebook.net/en_US/sdk.js#xfbml=1&version=v3.0";
    fjs.parentNode.insertBefore(js, fjs);
  }(document, 'script', 'facebook-jssdk'));</script>

  <!-- Your like button code -->
  <div class="fb-like" 
    data-href="https://www.your-domain.com/your-page.html" 
    data-layout="standard" 
    data-action="like" 
    data-show-faces="true">
  </div>
  <div id="fb-root"></div>
<script>(function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0];
  if (d.getElementById(id)) return;
  js = d.createElement(s); js.id = id;
  js.src = 'https://connect.facebook.net/en_US/sdk.js#xfbml=1&version=v3.2';
  fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));</script>

<div class="fb-like" data-href="https://developers.facebook.com/docs/plugins/" data-layout="standard" data-action="like" data-size="small" data-show-faces="true" data-share="true"></div>


{% endblock %}

templates/home1.html
<!-- templates/home.html-->
{% extends 'base.html' %}

{% block title %}Home{% endblock %}

{% block content %}
{% if user.is_authenticated %}
  Hi {{ user.username }}!
  <p><a href="{% url 'logout' %}">logout</a></p>
{% else %}
  <p>You are not logged in</p>
  <a href="{% url 'login' %}">login</a>
{% endif %}
{% endblock %}

templates/location.html
<!DOCTYPE html>
<html>
  <head>
    <style>
       /* Set the size of the div element that contains the map */
      #map {
        height: 400px;  /* The height is 400 pixels */
        width: 100%;  /* The width is the width of the web page */
       }
    </style>
  </head>
  <body>
 <div class="mapouter"><div class="gmap_canvas"><iframe width="600" height="600" id="gmap_canvas" src="https://maps.google.com/maps?q=tutepani&t=&z=13&ie=UTF8&iwloc=&output=embed" frameborder="0" scrolling="no" marginheight="0" marginwidth="0"></iframe><a href="https://www.pureblack.de/webdesign/"></a></div><style>.mapouter{text-align:right;height:600px;width:600px;}.gmap_canvas {overflow:hidden;background:none!important;height:600px;width:600px;}</style></div>

    <iframe width="560" height="315" src="https://www.youtube.com/embed/blH_EIVfEsA" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
  </body>
</html>

templates/login.html
{% extends 'base.html' %}
{% load static %}



{% block content %}

<h3>Login Form</h3>
<form method="POST">
  {% csrf_token %}
  {{ form.as_p }}
  <button type="submit">Login</button>
  {% if errors %}
  <li>{{errors}}</li>
  {% endif %}
</form>
{% endblock %}

templates/movie.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
{% for mov in movie %}
{{mov.name}},
{{mov.genre_choices}}

<!-- {{ Movie.get_genre_choices_display }} -->
{% endfor %}
{% endblock %}

templates/moviecreate.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<br>
<h3>Book Registration Form </h3>
<form method = "POST" enctype="multipart/form-data">
{% csrf_token %}

{{form.as_p}}
<button>Create</button>
</form>
{% endblock %}

templates/moviedetail.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<p>{{movie.id}}</p>
<p>{{movie.name}}</p>
<p>{{movie.director}}</p>
<p>{{movie.release_date}}</p>
<li>{{movie.actor}}</li>
<li>{{movie.run_time}}</li>
<li>{{movie.writer}}</li>
<li>{{movie.created_date}}</li>
<li>{{movie.runtime}}</li>
<li>{{movie.language}}</li>
<li>{{movie.rating}}</li>
<p><img src="{{movie.poster.url}}" class="img-fluid" width="200px">/p>
{% endblock %}

templates/movielist.html
{% extends 'base.html' %}
{% load static %}
{% block home %}active{% endblock %}
{% block content %}
 <div class="container-fluid">
	<table class="table table-striped table-bordered">
		<thead class="table-primary">
           	<tr>
        		<th>SN.</th>
        		<th>Name</th>
        		<th>Director</th>
        		<th>Releasae Date</th>
        		<th>Actors</th>
        		<th>Rating</th>
        		<th>Language</th>
        		<th>Runtime</th>
        		<th>Genre</th>
        		<th>Poster</th>
                <th>Action</th>
        	</tr>
    	</thead>
    	<tbody>
        	{% for movie in movielist %}
        	<tr>
                <td>{{forloop.counter}}</td>
            	<td><a href="{% url 'blogapp:moviedetail' movie.id %}">{{movie.name}}</a></td>
        		<td>{{movie.director}}</td>
        		<td>{{movie.release_date}}</td>
        		<td>{{movie.actor}}</td>
        		<td>{{movie.rating}}</td>
        		<td>{{movie.language}}</td>
        		<td>{{movie.run_time}}</td>
        		<td>{{movie.genre_choices}}</td>
        		<td><img src="{{movie.poster.url}}" class="img-fluid" width="200px"></td>
        		<td><a href="{% url 'blogapp:movieupdate' movie.id %}"> Update</a></td>
         	</tr>
            {% endfor %}
	   </tbody>
	</table>
</div>

{% endblock %}

templates/news.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
{% for news in news%}
<tr>
      <th scope="col">{{news.language}}</th>
<!-- 	  <th scope="col">{{news.title}}</th>
      <th scope="col">{{news.content}}</th>
      <th scope="col">{{news.image}}</th>
      <th scope="col"><img src="{{news.image.url}}" class="img-fluid" width="600px" height="400x"></th> -->
</tr>
{% endfor %}
{% endblock %}

templates/searchresult.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
{% if slist %}
<ul>
	{% for student in slist %}
	<li><a href="{% url 'blogapp:studentdetail' student.id %}">{{student.name}} </a></li>
	{% endfor %}
</ul>
{% else %}
<p>Nothing matched your search criteria.</p>
{% endif %}
{% endblock %}

templates/studentdelete.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<form method="POST">
{% csrf_token %}
	<h4> Are you sure??</h4>
	<button type="submit">OK</button>
</form>
{% endblock %}

templates/studentdetail.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<tr>
      <th scope="col">{{student.id}}</th>
      <th scope="col">{{student.name}}</th>
      <th scope="col">{{student.address}}</th>
      <th scope="col"><img src="{{student.image.url}}" class="img-fluid" width="200px"></th>
</tr>
{% endblock %}